name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: lukka/get-cmake@latest
    - name: Setup anew (or from cache) vcpkg (and does not build any package)
      uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                # action you need, `v11` in this case to stay up
                                # to date with fixes on the v11 branch.

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .

    - name: Test
      run: python tests/test.py
